name: build-docker-image
on : [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "GH_ENTERPRISE_TOKEN=${{ secrets.GITHUB_TOKEN }} docker build --tag docker-actions-example:latest --file build/package/Dockerfile ."
      - run: "docker run --rm docker-actions-example:latest hello world"
