name: build-docker-image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build/package/scripts/docker-build
        env:
          DOCKER_BUILDKIT: 1
          GH_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ./build/package/scripts/docker-run git clone git@github.com:rks/readme-readme-readme.git clone-run
        env:
          DEBUG: "1"
          GH_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
