name: build-docker-image
on : [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "docker build --tag docker-actions-example:latest --file build/package/Dockerfile --secret id=SAMPLE --secret id=GITHUB_TOKEN ."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAMPLE: sample
      - run: "docker run --rm --env SAMPLE --env GITHUB_TOKEN docker-actions-example:latest hello world"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAMPLE: sample
