name: build-docker-image
on : [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: "docker build --tag docker-actions-example:latest --file build/package/Dockerfile ."
      - run: "docker run --rm docker-actions-example:latest hello world"
