name: build-docker-image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
             mkdir --parents $HOME/.ssh
             ssh-keyscan github.com >> $HOME/.ssh/known_hosts 2> /dev/null
             echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
             chmod 600 $HOME/.ssh/id_ed25519
             eval $(ssh-agent -a $SSH_AUTH_SOCK) > /dev/null
             env | sort
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
