name: build-docker-image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
             echo $HOME
             mkdir --parents $HOME/.ssh
             ssh-keyscan github.com >> $HOME/.ssh/known_hosts
             echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
             chmod 600 $HOME/.ssh/id_ed25519
             ssh-agent -a $SSH_AUTH_SOCK
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
